apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./deploy/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: filipeqs/nexusfit.auth.api
      context: src/Services/Auth/NexusFit.Auth.API/
      docker:
        dockerfile: Dockerfile
    - image: filipeqs/nexusfit.angular-ui
      context: src/Web/WebSPA/
      docker:
        dockerfile: Dockerfile
