apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./deploy/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: filipeqs/nexusfit.auth.api
          context: src/Services/Auth/NexusFit.Auth.API/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              manual:
                  - src: '**/*.cs'
                    dest: .
        - image: filipeqs/nexusfit.exercises.api
          context: src/Services/Exercises/NexusFit.Exercises.API/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              manual:
                  - src: '**/*.cs'
                    dest: .
        - image: filipeqs/nexusfit.angular-ui
          context: src/Web/WebSPA/
          docker:
              dockerfile: Dockerfile.dev
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
                  - src: 'src/**/*.html'
                    dest: .
                  - src: 'src/**/*.scss'
                    dest: .
