version: '3.4'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

    authdb:
        image: mcr.microsoft.com/mssql/server:2022-latest

    kibana:
        image: docker.elastic.co/kibana/kibana:7.9.2

    auth.api:
        image: ${DOCKER_REGISTRY-}nexusfitauthapi
        build:
            context: Services/Auth/NexusFit.Auth.API
            dockerfile: Dockerfile.dev

    angular-ui:
        image: ${DOCKER_REGISTRY-}nexusfit-ui
        build:
            context: Web/WebSPA
            dockerfile: Dockerfile.dev

volumes:
    elasticsearch-data:
